### ISSUE TITLE
Add hiera data example

### ISSUE THREAD

**Issue by rnelson0** [rnelson0/puppet-local_user#14]
This will help users see how to format for hiera.

Is it possible that using hiera data in rspec would help with rspec AND with an example?

**Comment by bbriggs** [comment]
I don't know anything _at all_ about rspec, but I can drop in a hiera example. I think mine may be useful for showing how to separate users into groups (in the organizational sense, not the linux-y one).

**Comment by rnelson0** [comment]
@bbriggs I added an example, but feel free to add a more complicated one if you want!
