### ISSUE TITLE
Comment should not be a required parameter

### ISSUE THREAD

**Issue by bbriggs** [rnelson0/puppet-local_user#15]
Making the comment field a required parameter is in my opinion unnecessarily opinionated (see what I did there?). The comment field is merely informational and does not affect the functionality of the local user on the node.

**Comment by bbriggs** [comment]
Gonna try to work on this today

**Comment by rnelson0** [comment]
@bbriggs are you still working on this?

**Comment by bbriggs** [comment]
I'll send you a PR on it today.
