### ISSUE TITLE
Fix PuppetLabs linter complaints

### ISSUE THREAD

**Issue by bbriggs** [rnelson0/puppet-local_user#24]
Puppet Forge's linter is complaining about one issue that is lowering the quality score:
` String containing only a variable - 1 occurrence.`

I'd like to go ahead and find and fix this one if I could.

**Comment by rnelson0** [comment]
Awesome! I think a [controlcomment](http://puppet-lint.com/controlcomments/) will handle that.

**Comment by rnelson0** [comment]
I've learned that the Forge does not recognize controlcomments (https://tickets.puppetlabs.com/browse/FORGE-233), and "fixing" this just creates a different lint warning. We can open this anew if that decision is changed.
