### ISSUE TITLE
Submit for Puppet Approved status

### ISSUE THREAD

**Issue by rnelson0** [rnelson0/puppet-local_user#28]
I've decided to submit for Puppet Approved status. Even if the module doesn't make it, it will hopefully result in a more polished module.

**Comment by rnelson0** [comment]
Ticket opened: https://tickets.puppetlabs.com/browse/MODULES-3002

**Comment by bbriggs** [comment]
Can you set this as a milestone and create issues for people to resolve?

**Comment by rnelson0** [comment]
Milestone set. Issues will be created once I get feedback on it!

**Comment by bbriggs** [comment]
+1

**Comment by rnelson0** [comment]
The request was denied as [puppetlabs/accounts](https://forge.puppetlabs.com/puppetlabs/accounts) is already Supported. That's okay, we'll still try and make the module better. Maybe the addition of Windows management will change things.
