### ISSUE TITLE
Password not updated

### ISSUE THREAD

**Issue by jmaschtaler** [rnelson0/puppet-local_user#47]
Hi,

password won't be updated when an encrypted string has been set manually on host like

$6$sdI1fiR1$D1yU1ar/esZL5JrkIRF05U8bgQG3TfsEuDX/UwVO1KqE11b3pd1ejvn/eMkMSO4k9KbAaYDuqZ6RbqSGTslat0

best,
Jörg

**Comment by jmaschtaler** [comment]
Hi,

sorry for late answering.

Yes, there is another use case:
- Allow temporary access for users via puppet.

Cheers,
Jörg

**Comment by rnelson0** [comment]
If you want to manage the user's passwords for them, the built in user resource, or another user-related module, may be more appropriate for that use case.
