### ISSUE TITLE
FeatureRequest: User SSH Public Keys

### ISSUE THREAD

**Issue by cdenneen** [rnelson0/puppet-local_user#5]
Integrate ssh public keys arra.
Similar to accounts::user or pe_acounts::user

https://docs.puppetlabs.com/pe/latest/accounts_user_type.html

**Comment by rnelson0** [comment]
@cdenneen I submitted a PR on the sshkey branch. I am still traveling. It passes rspec tests but I haven't done any real testing. If you'd like to test it, please let me know how it works.

**Comment by rnelson0** [comment]
@cdenneen Have you had a chance to try this? I had another request for this recently but still haven't had time to test myself.

**Comment by cdenneen** [comment]
@rnelson0 I have not had a chance to yet.

**Comment by rnelson0** [comment]
@cdenneen PR6 is merged, this issue is resolved.
