### ISSUE TITLE
FeatureRequest: Manage Windows local users

### ISSUE THREAD

**Issue by cmug81** [rnelson0/puppet-local_user#7]
I'd like to manage basic aspects of local accounts on Windows. Please add support for that.

**Comment by rnelson0** [comment]
This is planned but I have no ETA. I welcome any PRs!

**Comment by matthewrstone** [comment]
I could take a crack at the Windows functionality.  Any particular definition of "basic aspects"?

**Comment by rnelson0** [comment]
Let's say, a user that can log in at the console, and go from there!
>
>

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by rnelson0** [comment]
@matthewrstone Have you had a chance to look at this feature yet?

**Comment by matthewrstone** [comment]
Yeah, sorry, been slacking a bit due to workload.  I got a bit hung trying to figure out how to encrypt the pw without external vaults, but if I leave that out I'd have something together shortly.

**Comment by rnelson0** [comment]
That would be a great starting point at least!

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by bbriggs** [comment]
By "encrypt password without external vaults" do you mean something like Hiera eyaml could provide?

**Comment by matthewrstone** [comment]
Well, yeah, kind of. As far as I remember, eyaml encrypts on disk but not in catalog, node_encrypt would encrypt in catalog, but I was looking at the ability to use SecureString in PS to manage the decryption of the hash on the local side. I built a PS function to create and encrypt a password based on a key and ship that to Puppet, but I also need to ship the key to decrypt it.  If you can plug the key and the password hash into Puppet it would actually work. Either way, the key is going to be exposed somewhere whether I embed it in hiera, the registry, wherever, so I went a little too far down the rabbit hole where plain text would probably suffice for now.

**Comment by rnelson0** [comment]
One thing IT has definitely taught me is that rabbit holes have no bottoms :)

**Comment by rnelson0** [comment]
@matthewrstone Just checking in for status. Anything I can help with?

**Comment by matthewrstone** [comment]
Doh!  Sorry, changed gigs and had to setup all my Windows dev stuff again.  Should have a branch up today/tomorrow to start testing.

**Comment by matthewrstone** [comment]
I've got something I can commit but don't have perms to push a branch apparently.  Any preferred method to get it contributed?

**Comment by rnelson0** [comment]
@matthewrstone Can you fork the repo and push a branch to your fork, then submit a PR?

**Comment by bbriggs** [comment]
Can we move this to "in progress" on Waffle?

**Comment by cmug81** [comment]
I assume this is done, so closing out :-)
